# This is a generated file. Not intended for manual editing.
services:
  bookify.api:
    build:
      context: "D:\\Devs\\Bookify"
      dockerfile: "src/Bookify.Api/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Bookify.Api.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "bookifyapi:dev"
    ports: []
    volumes:
    - "C:\\Users\\kosta\\AppData\\Roaming\\Microsoft\\UserSecrets:/home/app/.microsoft/usersecrets"
    - "C:\\Users\\kosta\\.nuget\\packages:/home/app/.nuget/packages"
    - "D:\\Devs\\Bookify\\src\\Bookify.Api:/app:rw"
    - "D:\\Devs\\Bookify:/src:rw"
    working_dir: "/app"
